Repository synyx/tuwat, pull requests merged in 2023-12, with the labels that each got.

#170 Update go version
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: dependencies, ci/cd

#172 documentation, describe multi-dashboard feature
  README.md
  docs/config/dashboards/drafts.toml
  docs/config/dashboards/no-drafts.toml
  docs/dashboards.md
  docs/rules.md
Labels: documentation

#171 icinga2, add host groups to services
  pkg/connectors/icinga2/connector.go
  pkg/connectors/icinga2/connector_test.go
Labels: enhancement, go

#167 Bind to all interfaces as default
  pkg/config/config.go
Labels: go, sec

#173 Fix 1.1 filtering
  pkg/aggregation/aggregator.go
  pkg/aggregation/aggregator_test.go
  pkg/config/rule_matching.go
  pkg/config/rule_matching_test.go
Labels: bug, go
